4.6 lth
RT-Thread-packages/paho-mqtt pull request #57
Opened 2023-04-06 10:19 UTC by d1zzy126

2023-04-06 11:43 UTC, d1zzy126 commented
修复了对mqtt_msg的内存分配中，当msg_len超出缓冲区的大小时，离开函数并且返回报错内容`PAHO_BUFFER_OVERFLOW`。

2023-04-06 18:44 UTC, mysterywolf approved these changes

2023-04-07 08:02 UTC, mysterywolf requested changes

2023-04-07 08:02 UTC, mysterywolf commented on MQTTClient-RT/paho_mqtt_pipe.c
> +        LOG_E("Message is too long %d:%d.", msg_len, c->buf_size);
使用LOG_x需要在这个文件开头加个tag:
参见：https://github.com/RT-Thread/rt-thread/blob/master/components/libc/compilers/common/ctime.c#L39-L41

2023-04-07 08:02 UTC, mysterywolf commented on MQTTClient-RT/paho_mqtt_pipe.c
> +        LOG_E("Message is too long %d:%d.", msg_len, c->buf_size);
tag可以使: "paho-mqtt"

2023-04-07 17:49 UTC, mysterywolf commented on MQTTClient-RT/paho_mqtt_udp.c
> +     if(msg_len >= c->buf_size)
可否阐述一下`msg_len >= c->buf_size` 在哪里受到了影响？

2023-04-13 02:55 UTC, d1zzy126 commented on MQTTClient-RT/paho_mqtt_udp.c
> +     if(msg_len >= c->buf_size)
与MQTT_CMD中的cmd_len判断相似，通过判断可以从输出中反应是cmd和msg长度溢出导致的异常还是rt_malloc内部分配失败导致的异常。

2023-04-13 03:02 UTC, mysterywolf commented
请处理一下冲突 谢谢~

2023-04-13 05:12 UTC, d1zzy126 commented on MQTTClient-RT/paho_mqtt_pipe.c
> +        LOG_E("Message is too long %d:%d.", msg_len, c->buf_size);
[https://github.com/d1zzy126/rt-thread/blob/master/include/rtdbg.h#L67-L76](url)
这里定义的是`DBG_SECTION_NAME`没有宏定义才会被`DBG_TAG`影响，我觉得这里是否不需要再加一个tag

2023-04-13 05:20 UTC, d1zzy126 commented on MQTTClient-RT/paho_mqtt_pipe.c
> +        LOG_E("Message is too long %d:%d.", msg_len, c->buf_size);
[`(https://github.com/d1zzy126/rt-thread/blob/d7ef1d1b4e3eabfa67a591cdf88f2a9f1f5fd6f3/include/rtdbg.h#L67-L77)`](https://github.com/d1zzy126/rt-thread/blob/d7ef1d1b4e3eabfa67a591cdf88f2a9f1f5fd6f3/include/rtdbg.h#L67-L77)

rtdbg.h中定义的是`DBG_SECTION_NAME`没有宏定义才会被`DBG_TAG`影响，我觉得这里是否不需要再加一个tag

2023-04-13 05:21 UTC, d1zzy126 commented
> 请处理一下冲突 谢谢~
之前的更改有误，已经撤销错误修改

2023-04-13 14:26 UTC, mysterywolf commented
你好 请处理一下冲突~ 代码有冲突无法合并

2023-04-15 00:30 UTC, mysterywolf commented on MQTTClient-RT/paho_mqtt_udp.c
> +    msg_len = sizeof(MQTTMessage) + message->payloadlen + strlen(topicName) + 1;
此处有问题，又将别人修改过的内容revert回来了 topicName已经被改成topic了 和此pr形成了冲突https://github.com/RT-Thread-packages/paho-mqtt/pull/55

2023-04-23 08:14 UTC, d1zzy126 commented on MQTTClient-RT/paho_mqtt_udp.c
> +    msg_len = sizeof(MQTTMessage) + message->payloadlen + strlen(topicName) + 1;
抱歉，现在才看到，已修改。

2023-06-12 09:43 UTC, Guozhanxin approved these changes

2023-06-12 09:44 UTC, merged